/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_spring_ndkdemo_MainActivity */

#ifndef _Included_com_spring_ndkdemo_MainActivity
#define _Included_com_spring_ndkdemo_MainActivity
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_spring_ndkdemo_MainActivity
 * Method:    getStrFromJNI
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spring_ndkdemo_MainActivity_getStrFromJNI
  (JNIEnv *, jobject);

/*
 * Class:     com_spring_ndkdemo_MainActivity
 * Method:    verificationPackage
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spring_ndkdemo_MainActivity_verificationPackage
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_spring_ndkdemo_MainActivity
 * Method:    verificationSign
 * Signature: (Ljava/lang/Object;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_spring_ndkdemo_MainActivity_verificationSign
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
